image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: version-v5.2.5@sha256:22c012bcc43cde544532e7797da678ffd0dab76d3afeec0a2906adfae6767256

  # PASSWORD: password

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
