image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: version-2.7.3-r5@sha256:a10ca4e48e053a1969e5256269e6d6aadcfb719f7b6cee444424028c74a6a008

env:
  PUID: 568

strategy:
  type: Recreate

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
