# Default values for Jackett.

image:
  repository: ghcr.io/truecharts/pihole
  pullPolicy: IfNotPresent
  tag: v2021.10.1@sha256:406a7368955ed3248a924bcb9c578d8554793048e025deb59f03caf6fd3f17c4

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  allowPrivilegeEscalation: true

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envFrom:
  - configMapRef:
      name: pihole-env

service:
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
  dns-tcp:
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        port: 53
        targetPort: 53
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        protocol: UDP
        port: 53
        targetPort: 53

pihole:
  WEBPASSWORD: "somepassword"
  DNS1: "9.9.9.9"
  DNS2: "149.112.112.112"

persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"
