# Default values for Sabnzbd.

image:
  repository: ghcr.io/k8s-at-home/sabnzbd
  pullPolicy: IfNotPresent
  tag: v3.4.2@sha256:26dc34fc8fbad6a678993ee03742ede43d5b1ec079ac15990063c2861375e597

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

env: {}
  # TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"
