# Default values for nzbget.

image:
  repository: ghcr.io/k8s-at-home/nzbget
  pullPolicy: IfNotPresent
  tag: v21.1@sha256:a000653a171eb6779f2d87ddbf0cde5e0ed71a6bd89b35c1047fe67757b3ab1e

service:
  main:
    ports:
      main:
        port: 6789
        targetPort: 6789

probes:
  liveness:
    enabled: false

  readiness:
    enabled: false

  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
