image:
  repository: ghcr.io/linuxserver/medusa
  pullPolicy: IfNotPresent
  tag: 0.5.20@sha256:24f43e0e6a46872b49f4713f0a8bf98f6b64bfa2a7ced1cb33d54adea26ed4e5
env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8081
        targetPort: 8081

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
