image:
  repository: ghcr.io/truecharts/collabora
  tag: v6.4.14.3@sha256:d4a55425927736cb167a8df37ba6f2a60c0e3e0bacc0ee2496ecb5e535176f60
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 104
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 9980
        targetPort: 9980

env:
  domain: nextcloud\.domain\.tld
  dictionaries: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
  username: admin
  password: changeme
  extra_params: "-o:welcome.enable=false -o:user_interface.mode=notebookbar -o:ssl.termination=true -o:ssl.enable=false"
  server_name: collabora\.domain\.tld
