# Default values for Syncthing.

image:
  repository: ghcr.io/truecharts/syncthing
  pullPolicy: IfNotPresent
  tag: v1.18.4@sha256:cc2bd691927ec19b9aac2d4a3e2330cb0ce9458dda761ead7dddd5f2d8338221

service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: UDP
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing/"
