image:
  # -- image repository
  repository: xirixiz/dsmr-reader-docker
  # -- image tag
  tag: latest-2021.09.02-amd64@sha256:4858edb1ae63a20639a0ef9c51c7b2cf599686db5c582ead7b37b2a288122935
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://github.com/xirixiz/dsmr-reader-docker#dsmr-reader---environment-variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envTpl:
  DJANGO_TIME_ZONE: "{{ .Values.env.TZ }}"
  DJANGO_DATABASE_ENGINE: "django.db.backends.postgresql"
  DJANGO_DATABASE_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DJANGO_DATABASE_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DJANGO_DATABASE_PORT: "5432"

envValueFrom:
  DJANGO_DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DJANGO_DATABASE_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
# -- Enable and configure postgresql database subchart under this key.
# @default -- See values.yaml
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: dsmr-reader
  postgresqlDatabase: dsmr-reader
