# Default values for Ombi.

image:
  repository: ghcr.io/truecharts/ombi
  pullPolicy: IfNotPresent
  tag: v4.0.1482@sha256:0fa4e81029d9adef9d773ce99db13ff3039fd087d58d7266cbcfd7462e7afc56

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579

env: {}
  # TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"


# Enabled mariadb
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
  primary:
    persistence:
      enabled: false
