# Fake external service image
image:
  repository: ghcr.io/truecharts/bs
  pullPolicy: IfNotPresent
  tag: v0.66.6@sha256:666

# Disable Deployment
controller:
  enabled: false

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    ports:
      main:
        Type: HTTPS
        port: 443
        targetPort: 443
