image:
  repository: ghcr.io/linuxserver/piwigo
  pullPolicy: IfNotPresent
  tag: version-11.5.0@sha256:13aa1206583cf5ff5d20c6d9b0738bcf5de6907b27e96c334ff5e3b716e959d9

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
