# Default values for Bazarr.

image:
  repository: ghcr.io/k8s-at-home/bazarr
  pullPolicy: IfNotPresent
  tag: v1.0.1@sha256:8b785e187aa9e74bb7ef6cecad8dc3fbd5c905a638d496a90aaeb0a1dcd80cc1

service:
  main:
    ports:
      main:
        port: 6767
        targetPort: 6767

env: {}
  # TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"
