apiVersion: v2
appVersion: "RELEASE.20"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.3
description: Minio is a self-hosted S3 storage server
home: https://github.com/truecharts/apps/tree/master/charts/incubator/minio
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- minio
- s3
- storage
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: minio
sources:
- https://github.com/minio/minio
version: 0.0.6
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
