image:
  repository: ghcr.io/k8s-at-home/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.36@sha256:7dad2a3a0d4ca0156ab0aa2a718765455ea815bfcdd301348c047d477080a476

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    enabled: true
    ports:
      main:
        port: 9117
        targetPort: 9117
    portsList:
      - name: "extraport"
        enabled: true
        port: 9118
        targetPort: 9118

serviceList:
  - name: extraservice
    enabled: true
    portsList:
      - name: "extrasvcport"
        enabled: true
        port: 9119
        targetPort: 9119

env: {}
  # TZ: UTC
  # PUID: 1001


persistence:
  config:
    enabled: true
    mountPath: "/config"
    type: pvc
    accessMode: ReadWriteOnce
    size: "100Gi"
