# Default values for Jackett.

image:
  repository: ghcr.io/techno-tim/littlelink-server
  pullPolicy: IfNotPresent
  tag: latest@sha256:6d6bcbdd5e5a17b85f98a6ab42c95ba8f083dc8a2d7d2a3f4fcb28e446a57c4d

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

envFrom:
  - configMapRef:
      name: littlelinkconfig

littlelink:
  meta_title: "techno tim"
  meta_description: "techno tim link page"
  meta_author: "techno tim"
  theme: "dark"
  favicon_url: "https://pbs.twimg.com/profile_images/1286144221217316864/qiaskopb_200x200.jpg"
  avatar_url: "https://pbs.twimg.com/profile_images/1286144221217316864/qiaskopb_200x200.jpg"
  avatar_2x_url: "https://pbs.twimg.com/profile_images/1286144221217316864/qiaskopb_400x400.jpg"
  avatar_alt: "techno tim profile pic"
  name: "technotim"
  bio: "hey! just a place where you can connect with me!"
  github: "https://github.com/timothystewart6"
  twitter: "https://twitter.com/technotimlive"
  instagram: "https://www.instagram.com/techno.tim"
  youtube: "https://www.youtube.com/channel/ucok-ghyjcwznj3br4oxwh0a"
  twitch: "https://www.twitch.tv/technotim/"
  discord: "https://discord.gg/djkexrj"
  tiktok: "https://www.tiktok.com/@technotim"
  kit: "https://kit.co/technotim"
  footer: "thanks for stopping by!"
