#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/truecharts/flood
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v4.7.0@sha256:6ad4f3eb39e6b04d1632dd0436031377eb35759e0edcd56a95e5dd8c58c09ed8

# -- environment variables. See more environment variables in the [flood documentation] (https://github.com/jesec/flood/blob/v4.6.0/config.ts)
# Note: The environmental variables are not case sensitive (e.g. FLOOD_OPTION_port=FLOOD_OPTION_PORT).
# @default -- See below
env:
  # -- Where to store Flood's runtime files (eg. database)
  FLOOD_OPTION_RUNDIR: /data

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: "/data"
