# Default values for emby.

image:
  repository: ghcr.io/k8s-at-home/emby
  pullPolicy: IfNotPresent
  tag: v4.6.5.0@sha256:11b1f306d6309b60f16bf4292f9737c0a4a0020e93cfc1c0b36bc10b2680da40

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8096
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"
