image:
  repository: ghcr.io/linuxserver/headphones
  pullPolicy: IfNotPresent
  tag: version-58edc604@sha256:43f2d40be460ac59c6b80d6ea1307f14dad11379ac607b6752f84a758da6b118

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
