#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: tenstartups/ser2sock
  # -- image tag
  tag: latest@sha256:379d9338c720da30b63dc4cf2ecea07eb89dac7d62d5c79047294fffe97ae559
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://github.com/tenstartups/ser2sock) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Port where ser2sock listens
  LISTENER_PORT: "{{ .Values.service.main.ports.main.port }}"
  # -- Path to the serial device
  SERIAL_DEVICE: "{{ .Values.persistence.usb.mountPath }}"
  # -- Serial device baud rate
  BAUD_RATE: 115200

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10000
        targetPort: 10000

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - ser2sock-controller
