image:
  # -- image repository
  repository: traccar/traccar
  # -- image tag
  tag: 4.14@sha256:35e733a6a3cab6089cd7b28749ba3483f26d43d392a2606e416409d97d360a55
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [traccar documentation](https://www.traccar.org/configuration-file/)
# @default -- See below
env:
  # -- Set application to read environment variables
  CONFIG_USE_ENVIRONMENT_VARIABLES: true
  # -- Set application to log to stdout
  LOGGER_CONSOLE: true

envTpl:
  DATABASE_DRIVER: "org.postgresql.Driver"
  DATABASE_USER: "{{ .Values.postgresql.postgresqlUsername }}"

envValueFrom:
  DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DATABASE_URL:
    secretKeyRef:
      name: dbcreds
      key: jdbc

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 8082
        targetPort: 8082

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: "/opt/traccar/data"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: traccar
  postgresqlDatabase: traccar
