# Default values for jellyfin.

image:
  repository: ghcr.io/truecharts/jellyfin
  pullPolicy: IfNotPresent
  tag: v10.7.7@sha256:2fa78e734903d95f8b530d2f3203f5ce5d9ff891cc8a70c0e80e828e336b4abb

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8096
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"
