image:
  repository: ghcr.io/linuxserver/photoshow
  pullPolicy: IfNotPresent
  tag: version-48aabb98@sha256:c6f3575f271615c367edcf27c3c1b6b8d89c95a2ff333d44c5a982b7d7b251bb

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
