# Default values for Tautulli.

image:
  repository: ghcr.io/k8s-at-home/tautulli
  pullPolicy: IfNotPresent
  tag: v2.7.7@sha256:4ea617c30397c4651c3e5ac850d4f4d2d7bfc5d37ac6dec44c5d109258d4f03f

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

env: {}
  # TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"
