# Default values for node-red.

image:
  repository: ghcr.io/truecharts/node-red
  pullPolicy: IfNotPresent
  tag: v2.1.2@sha256:1bdc555a36417b165ed2ae1246a15321cdb476bfa1a0315c82d1931ad9beb04f

# See more environment varaibles in the node-red documentation
# https://nodered.org/docs/getting-started/docker
env: {}
  # TZ:
  # NODE_OPTIONS:
  # NODE_RED_ENABLE_PROJECTS:
  # NODE_RED_ENABLE_SAFE_MODE:
  # FLOWS:

service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880

persistence:
  data:
    enabled: true
    mountPath: "/data"
