# Default values for Sonarr.

image:
  repository: ghcr.io/truecharts/unpackerr
  pullPolicy: IfNotPresent
  tag: v0.9.8@sha256:2bf65067fea86c36438b741bfea1cec69faeea02dd4811c0d58e12243a263b24

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false

env: {}
  # TZ: UTC
  # PUID: 1001
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  downloads:
    enabled: true
    mountPath: "/downloads"
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    #
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
