# Default values for oscam

image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: version-11693@sha256:e97f9929c3a6caed6ee24ed9f1efdd4a8c29b4b2ba52205d3f8daebdaf7a9ea2

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 20

env:
  TZ: UTC
  PUID: 568

service:
  main:
    ports:
      main:
        port: 8888
        targetPort: 8888

persistence:
  config:
    enabled: true
    mountPath: "/config"

  varrun:
    enabled: true
