image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/tt-rss
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v1.9063.0@sha256:53e84ba1beaa012b6343115c03e2c3a3848965938bc42c8d7413d24aeb082c25

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

persistence:
  config:
    enabled: true
    mountPath: "/config"

# -- See more environment variables in the tt-rss documentation
# https://git.tt-rss.org/fox/tt-rss/src/branch/master/classes/config.php#L9
# @default -- See below.
env:
  # -- External URL you use to connect to the RSS (the one you enter in your browser)
  TTRSS_SELF_URL_PATH: ""

envTpl:
  TTRSS_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  TTRSS_DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  TTRSS_DB_PORT: "5432"

envValueFrom:
  TTRSS_DB_PASS:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  TTRSS_DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

# -- Configure the services for the chart here.
# @default -- See below.
service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

# @default -- see bellow
# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  # -- Postgres database user name
  postgresqlUsername: tt-rss
  # -- Postgres database password
  postgresqlDatabase: tt-rss
