image:
  repository: ghcr.io/linuxserver/muximux
  pullPolicy: IfNotPresent
  tag: version-057352e8@sha256:592471f458c3c03b608bd2a827431dd77493644edf6638429349e7b6e0290e4c

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
