image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: version-1.2.0-rcgit.29dfsg-1ubuntu1@sha256:d45c3ba938709a161dc6d0e9d72db82db71142684dcf6738dcb15d06f130e02b
env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
