# Default values for Navidrome.

image:
  repository: ghcr.io/truecharts/navidrome
  pullPolicy: IfNotPresent
  tag: v0.47.0@sha256:0ca8781ecf33f961d9e1157b8f0aa0ad8d69cde3dac99e8084bd34aa73094128

service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533

env:
  ND_SCANINTERVAL: "15m"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_MUSICFOLDER: "/music"

persistence:
  data:
    enabled: true
    mountPath: "/data"
