image:
  repository: ghcr.io/linuxserver/code-server
  pullPolicy: IfNotPresent
  tag: version-v3.11.1@sha256:a385ba5cb16136b14ae4cd99ca95c20ac77f9831ac3fb63937a1998e1d31be2a

# PASSWORD: password
# SUDO_PASSWORD: password
# HASHED_PASSWORD

env:
  PUID: 568
  # PROXY_DOMAIN: code-server.my.domain

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8443
        targetPort: 8443

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
