#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
# -- image repository
  repository: ghcr.io/truecharts/owncast
  # -- image tag
  tag: v0.0.10@sha256:59e455798cacf118a74184755b060f48bcc05dc56bb9d4f696bcc77f411f1ad0
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080
  rtmp:
    enabled: true
    externalTrafficPolicy: Local
    ports:
      rtmp:
        enabled: true
        port: 1935
        targetPort: 1935


# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/app/data"
