image:
  repository: bitnami/mariadb
  pullPolicy: IfNotPresent
  tag: 10.6.5@sha256:56644d687e906ae8311afb447210cf28335b4f4a394817d45e2de5b14f271381

controller:
  # -- Set the controller type.
  # Valid options are deployment, daemonset or statefulset
  type: statefulset
  # -- Number of desired pods
  replicas: 1
  # -- Set the controller upgrade strategy
  # For Deployments, valid values are Recreate (default) and RollingUpdate.
  # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
  # DaemonSets ignore this.
  strategy: RollingUpdate
  rollingUpdate:
    # -- Set deployment RollingUpdate max unavailable
    unavailable: 1
    # -- Set deployment RollingUpdate max surge
    surge:
    # -- Set statefulset RollingUpdate partition
    partition:
  # -- ReplicaSet revision history limit
  revisionHistoryLimit: 3

service:
  main:
    ports:
      main:
        port: 3306
        targetPort: 3306

securityContext:
  readOnlyRootFilesystem: false


podSecurityContext:
  runAsGroup: 0

volumeClaimTemplates:
  data:
    enabled: true
    mountPath: "/bitnami/mariadb"

# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own livenessProbe
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - /bin/bash
          - -ec
          - mysqladmin status -uroot -p"${MARIADB_ROOT_PASSWORD}"

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    # -- Enable the readiness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own readinessProbe
    custom: true
    # -- The spec field contains the values for the default readinessProbe.
    # If you selected `custom: true`, this field holds the definition of the readinessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - /bin/bash
          - -ec
          - mysqladmin status -uroot -p"${MARIADB_ROOT_PASSWORD}"
  # -- Startup probe configuration
  # @default -- See below
  startup:
    # -- Enable the startup probe
    enabled: true
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - /bin/bash
          - -ec
          - mysqladmin status -uroot -p"${MARIADB_ROOT_PASSWORD}"

mariadbPassword: "testpass"
mariadbUsername: "test"
mariadbDatabase: "test"
mariadbRootPassword: "testroot"
existingSecret: ""

envValueFrom:
  MARIADB_PASSWORD:
    secretKeyRef:
      name: '{{ ( tpl .Values.existingSecret $ ) | default ( include "common.names.fullname" . ) }}'
      key: "mariadb-password"
  MARIADB_ROOT_PASSWORD:
    secretKeyRef:
      name: '{{ ( tpl .Values.existingSecret $ ) | default ( include "common.names.fullname" . ) }}'
      key: "mariadb-root-password"

envTpl:
  MARIADB_USER: "{{ .Values.mariadbUsername }}"
  MARIADB_DATABASE: "{{ .Values.mariadbDatabase }}"
