# Default values for Plex.

image:
  repository: ghcr.io/k8s-at-home/plex
  pullPolicy: IfNotPresent
  tag: v1.24.5.5173-8dcc73a59@sha256:b651efe17214c1cc06345466a3db5f62c0b4b8f3e49e0083e19d04f13001abc6

service:
  main:
    ports:
      main:
        port: 32400
        targetPort: 32400

persistence:
  config:
    enabled: true
    mountPath: "/config"


env:
  ALLOWED_NETWORKS: "172.16.0.0/16"
