image:
  repository: ghcr.io/linuxserver/doublecommander
  pullPolicy: IfNotPresent
  tag: version-0.8.2-1@sha256:61800aec4066ab01d10bebf8a06de3f6a1b1fe7f9bc0c198d9aaad8770f85ce0

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
