# Default values for grocy.

image:
  repository: ghcr.io/linuxserver/grocy
  tag: version-v3.1.1@sha256:f67e4ce1c7498f5360d874955b0baf3b6b4ae88f5411094d32f7bfb93ddd4a5a
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

env: {}
  # TZ:
  # PUID:
persistence:
  config:
    enabled: true
    mountPath: "/config"
