# Default values for Bitwarden.

image:
  repository: ghcr.io/truecharts/freeradius
  pullPolicy: IfNotPresent
  tag: v3.0.23@sha256:21454da0a4f4950dd9b97e82de5b56556fdf2bf38f60ae427852b74a2622c972

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: UDP
        port: 1812
        targetPort: 1812
  accounting:
    enabled: true
    ports:
      accounting:
        enabled: true
        protocol: UDP
        port: 1813
        targetPort: 1813

# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    enabled: false

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    enabled: false

  # -- Startup probe configuration
  # @default -- See below
  startup:
    enabled: false

env: {}

persistence:
  config:
    enabled: true
    mountPath: "/etc/raddb"
