# Default values for Logitech Media Server.

image:
  repository: lmscommunity/logitechmediaserver
  pullPolicy: IfNotPresent
  tag: 8.3.0@sha256:a035d06f8d57af2deb3de7ee9d5d22d894b17d31a1dbd46f45844af20e6cfc5a
env:
  # Permissions Settings
  PUID: 568

envTpl:
  # Port to host the web service on. This will be the internal container port exposed and needs to be the same as the public service port.
  # The main http port always has to be a 1:1 mapping between external and internal port.
  # You can't just map it like -p 9002:9000, as Logitech Media Server is telling players on which port to connect.
  # Therefore if you have to use a different http port for LMS (other than 9000) you'll have to set the HTTP_PORT environment variable
  HTTP_PORT: "{{ .Values.service.main.ports.main.port }}"

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        # Please note that the main http port always has to be a 1:1 mapping between external and internal port.
        # You can't just map it like -p 7000:9000, as Logitech Media Server is telling players on which port to connect.
        # Therefore if you have to use a different http port for LMS (other than 9000) you'll have to set the HTTP_PORT environment variable
        targetPort: 7000
        port: 7000
  cli:
    enabled: true
    ports:
      cli:
        enabled: true
        targetPort: 9090
        port: 9090
  playertcp:
    enabled: true
    ports:
      slimprototcp:
        enabled: true
        targetPort: 3483
        port: 3483
  playerudp:
    enabled: true
    ports:
      slimprotoudp:
        enabled: true
        targetPort: 3483
        port: 3483

persistence:
  config:
    enabled: true
    mountPath: "/config"
