image:
  repository: ghcr.io/nicholaswilde/shorturl
  pullPolicy: IfNotPresent
  tag: version-v0.1.0@sha256:75fc450af5d2d07e5caebc6a01863a0aacdc15c1fbe57b3db46e3bd548226420

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8000
        targetPort: 8000

persistence:
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true
