image:
  repository: ghcr.io/linuxserver/filezilla
  pullPolicy: IfNotPresent
  tag: version-3.51.0-r1@sha256:5103cdd266ceb61cebabae6629e418570a5094e3f61ef2f405f6e24d4fc7f6a4

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
