apiVersion: v2
appVersion: "20211018"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.3
description: "PhotoPrism\xC2\xAE is a server-based application for browsing, organizing\
  \ and sharing your personal photo collection"
home: https://github.com/truechartsapps/tree/master/charts/stable/photoprism
icon: https://demo.photoprism.org/static/img/logo-avatar.svg
keywords:
- photos
- photoprism
- pictures
- sharing
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: photoprism
sources:
- https://github.com/photoprism/photoprism
- https://hub.docker.com/r/photoprism/photoprism
version: 5.0.12
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
