image:
  repository: ghcr.io/nicholaswilde/golinks
  pullPolicy: IfNotPresent
  tag: version-154c581@sha256:8e67b26324c5dc433210df8f2fb64317db3cbbe7db0b9e10c6e5bc3f3f7860e4
env: {}
  # SUGGEST=https://suggestqueries.google.com/complete/search?client=firefox&q=%s `# optional` \
  # TITLE=Search `# optional` \
  # URL=https://www.google.com/search?q=%s&btnK

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8000
        targetPort: 8000

persistence:
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true
