# Default values for Bitwarden.

image:
  repository: docker.io/nextcloud
  pullPolicy: IfNotPresent
  tag: 22.2.3@sha256:5512b02fca6533626ed0a1799b2090255357de9b269d0a04d8f7a6d582438ccc

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 33

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80
  hpb:
    enabled: true
    ports:
      hpb:
        enabled: true
        port: 7867
        targetPort: 7867

env:
  NEXTCLOUD_ADMIN_USER: "admin"
  NEXTCLOUD_ADMIN_PASSWORD: "adminpass"
  TRUSTED_PROXIES: "172.16.0.0/16"

envTpl:
  POSTGRES_DB: "{{ .Values.postgresql.postgresqlDatabase }}"
  POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername }}"

envFrom:
  - configMapRef:
      name: nextcloudconfig

envValueFrom:
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  POSTGRES_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainporthost
  REDIS_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_HOST_PASSWORD:
    secretKeyRef:
      name: rediscreds
      key: redis-password

persistence:
  data:
    enabled: true
    mountPath: "/var/www/html"
# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    custom: true
    # -- If a HTTP probe is used (default for HTTP/HTTPS services) this path is used
    # @default -- "/"
    spec:
      httpGet:
        path: /status.php
        port: 80
        httpHeaders:
        - name: Host
          value: "test.fakedomain.dns"

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    custom: true
    # -- If a HTTP probe is used (default for HTTP/HTTPS services) this path is used
    # @default -- "/"
    spec:
      httpGet:
        path: /status.php
        port: 80
        httpHeaders:
        - name: Host
          value: "test.fakedomain.dns"

  # -- Startup probe configuration
  # @default -- See below
  startup:
    custom: true
    # -- If a HTTP probe is used (default for HTTP/HTTPS services) this path is used
    # @default -- "/"
    spec:
      httpGet:
        path: /status.php
        port: 80
        httpHeaders:
        - name: Host
          value: "test.fakedomain.dns"

## Cronjob to execute Nextcloud background tasks
## ref: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#webcron
##
cronjob:
  # Every 5 minutes
  # Note: Setting this to any any other value than 5 minutes might
  #  cause issues with how nextcloud background jobs are executed
  schedule: "*/5 * * * *"
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: nextcloud
  postgresqlDatabase: nextcloud

# Enabled redis
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/redis
redis:
  enabled: true
  existingSecret: "rediscreds"
