image:
  repository: ghcr.io/linuxserver/cloud9
  pullPolicy: IfNotPresent
  tag: version-1.29.2@sha256:f2bc1b08e713f1600d374e2347db3963908703c6f6e926649c7a7af064dfa739

# USERNAME="" #optional
# PASSWORD="" #optional

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8000
        targetPort: 8000

persistence:
  code:
    enabled: true
    mountPath: "/code"
  varrun:
    enabled: true
