image:
  repository: ghcr.io/nicholaswilde/fossil
  pullPolicy: IfNotPresent
  tag: 2.15.1-ls4@sha256:a0a819ed2707e8e829dec371de0e166fbcf0499d3d12005880f603b2b95bf64d
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

persistence:
  varrun:
    enabled: true
