# Default values for Lidarr.

image:
  repository: ghcr.io/k8s-at-home/lidarr
  pullPolicy: IfNotPresent
  tag: v1.0.0.2255@sha256:54ebc1f90963b16889e9e1b915eced4efd45ae489805aa996faf519430a4322f

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8686
        targetPort: 8686

env: {}
  # TZ: UTC
  # PUID: 1001
probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:8686/api/v1/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"
