# Default values for nzbhydra.

image:
  repository: ghcr.io/k8s-at-home/nzbhydra2
  pullPolicy: IfNotPresent
  tag: v3.17.3@sha256:9c1a08356359e75051b03ec614b4df5f6f24558a183de6feacb3a5c2ff232b77

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076

env: {}
  # TZ: UTC
  # PUID: 1001
probes:
  liveness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/livenessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  readiness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
  startup:
    custom: true
    enabled: true
    spec:
      failureThreshold: 5
      httpGet:
        path: /actuator/health/readinessState
        port: main
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"
