# Default values for Jackett.

image:
  repository: deepquestai/deepstack
  pullPolicy: IfNotPresent
  tag: cpu-2021.09.1@sha256:359dc8c6c5056891b2a4f419902616b8b8b9bc9068b0c20fd40e13bc7a5583b5

service:
  main:
    ports:
      main:
        port: 5000
        targetPort: 5000

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envTpl:
  # Permissions Settings
  USER_ID: "{{ .Values.env.PUID }}"
env:
  PUID: 568

  # TZ: UTC
  VISION-FACE: "True"
  VISION-DETECTION: "True"
  VISION-SCENE: "True"
  # Path to custom models (needs to be on documentation)
  MODELSTORE-DETECTION: "/modelstore/detection"
  # High|Medium|Low
  MODE: "High"

persistence:
  data:
    enabled: true
    mountPath: "/datastore"
