#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/haste-server
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: latest@sha256:827aa2f2389d94a522e333080fa8cbc0e0a487c5681173caca785b3b6b9e5b01

# -- environment variables. See [image docs](https://github.com/seejohnrun/haste-server) for more details.
# @default -- See below
env:
  # -- filepath for persistance
  STORAGE_FILEPATH: "/config"
  # -- sets backend
  STORAGE_TYPE: "file"

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 7777
        targetPort: 7777

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
