#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/xteve
  # -- image tag
  tag: v2.2.0.200@sha256:e1afd6ea29e9b680191d8024f41eb495bc8fc7c2870fa36fbfa4f684c9a708dc
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

service:
  main:
    ports:
      main:
        port: 34400
        targetPort: 34400

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
