#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/truecharts/thelounge
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v4.3.0@sha256:1a017ca7ee4ebcb8eadbbd416e21366e73084ddea68c8160f7f3f7e9eeae8f3b

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- environment variables. See [image docs](https://hub.docker.com/r/thelounge/thelounge/) for more details.
# @default -- See below
env:
  THELOUNGE_HOME: "/config"

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 9000
        targetPort: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
