image:
  repository: ghcr.io/linuxserver/pixapop
  pullPolicy: IfNotPresent
  tag: v1.2-ls15@sha256:605ebc091fa14b4ba82ceadda7f35c186d514e649c97913605384027c2750f4f
env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
