# Default values for fireflyIII.

image:
  repository: fireflyiii/core
  pullPolicy: IfNotPresent
  tag: version-5.5.12@sha256:9a1f87a8ad38694675390756be9686fe9d8ba941fe1f145641626135c7eb5e4b

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

probes:
  liveness:
    path: "/login"

  readiness:
    path: "/login"

  startup:
    path: "/login"

env:
  DB_USERNAME: firefly
  DB_DATABASE: firefly
  DB_CONNECTION: pgsql
  DB_PORT: 5432
  APP_KEY: AGcfkCUS233ZWmBXztYbdyCs2u7kkz55

envValueFrom:
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password

persistence:
  data:
    enabled: true
    mountPath: "/var/www/html/storage/upload"


# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: firefly
  postgresqlDatabase: firefly
