apiVersion: v2
appVersion: "5.5.12"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://truecharts.org/
  version: 6.0.10
deprecated: false
description: A free and open source personal finance manager
home: https://github.com/firefly-iii/firefly-iii/
icon: https://www.firefly-iii.org/assets/logo/color.png
keywords:
- fireflyiii
- finacial
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: fireflyiii
sources:
- https://github.com/firefly-iii/firefly-iii/
type: application
version: 13.0.3
annotations:
  truecharts.org/catagories: |
    - finacial
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
