# Default values for deluge.

image:
  repository: ghcr.io/linuxserver/deluge
  pullPolicy: IfNotPresent
  tag: version-2.0.3-2201906121747ubuntu18.04.1@sha256:2ce561a95e7be890c1daf718e85e37fd58d792ac86ec031d1dd22f85e5311469

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8112
        targetPort: 8112
  torrent:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 51413
        targetPort: 51413
  torrent-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 51413
        targetPort: 51413
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
