apiVersion: v2
appVersion: "900b76a"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.3
description: A self-hosted well uh wiki engine or content management system.
home: https://github.com/truecharts/apps/tree/master/charts/stable/wiki
icon: ''
keywords:
- wiki
- web
- blog
- cms
- app
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: wiki
sources:
- https://github.com/prologic/wiki
- https://github.com/nicholaswilde/docker-wiki
type: application
version: 1.0.12
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
