# Default values for Calibre-Web.

image:
  repository: ghcr.io/linuxserver/calibre-web
  pullPolicy: IfNotPresent
  tag: version-0.6.12@sha256:938810eca3d3137221308afe9095773c8552a457dc0943abd0aec5613242b0b6

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8083
        targetPort: 8083

env: {}
  # TZ:
  # PUID:

  # UMASK:
  # DOCKER_MODS:

persistence:
  config:
    enabled: true
    mountPath: "/config"
