image:
  repository: ghcr.io/linuxserver/sickgear
  pullPolicy: IfNotPresent
  tag: version-release_0.25.4@sha256:ad0e59d0590906f7c303926a316a357c8541986205c40cae5848a1ea5e552399

env:
  PUID: 568

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8081
        targetPort: 8081

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
