apiVersion: v2
appVersion: "latest"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.3
deprecated: false
description: Discord bot that provides metrics from a Discord server
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/promcord
keywords:
- promcord
- discord
- metrics
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: promcord
sources:
  - https://github.com/nimarion/promcord
type: application
version: 0.0.1
annotations:
  truecharts.org/catagories: |
    - metrics
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
