image:
  # -- image repository
  repository: ghcr.io/k8s-at-home/apache-musicindex
  # -- image tag
  tag: v1.4.1-2@sha256:c8b5cf5fbf4bbf097fb516f82bfc3ecb1ad971e8059dc9722b4d10bb7d7faee7
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Allows to start web server on ports 80 and 443
# @default -- See values.yaml
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 80
