# Default values for Radarr.

image:
  repository: ghcr.io/k8s-at-home/radarr
  pullPolicy: IfNotPresent
  tag: v3.2.2.5080@sha256:b03562bacb117ab654dca5c6bcc61d013a40fe54e9fa1f563cd1c72899f77137

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 7878
        targetPort: 7878

env: {}
  # TZ: UTC
  # PUID: 1001
probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"
