image:
  repository: ghcr.io/truecharts/handbrake
  tag: v1.24.2@sha256:312ddf5ec046fd0ca3f84015b55c8b4cbe1d6e8340ffcaf244489592a3fc92da
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 5800
        targetPort: 5800
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 5900
        targetPort: 5900
        protocol: "TCP"

# All values here are set as the docker defaults.
envTpl:
  # Permissions Settings
  USER_ID: "{{ .Values.env.PUID }}"
env:
  # Permissions Settings
  PUID: 568

  # General Settings
  KEEP_APP_RUNNING: "0"
  CLEAN_TMP_DIR: "1"
  # GUI Settings
  DISPLAY_WIDTH: "1280"
  DISPLAY_HEIGHT: "768"
  SECURE_CONNECTION: "0"
  VNC_PASSWORD: ""
  # Automated Conversion Preset
  AUTOMATED_CONVERSION_PRESET: "General/Very Fast 1080p30"
  AUTOMATED_CONVERSION_FORMAT: "mp4"
  AUTOMATED_CONVERSION_KEEP_SOURCE: "1"
  AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: "ignore"

persistence:
  config:
    enabled: true
    mountPath: "/config"
